const C=window.INDHUJA_CONFIG;let db;
function init(){if(!C.SUPABASE_URL.startsWith("http")){msg.textContent="Add Supabase URL and key in config.js first.";return false}db=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_KEY);return true}
function setLogin(v){login.hidden=!v;app.hidden=v}
loginBtn.onclick=async()=>{if(!init())return;const {error}=await db.auth.signInWithPassword({email:email.value,password:password.value});msg.textContent=error?.message||"";if(!error){setLogin(false);load()}}
logout.onclick=async()=>{await db.auth.signOut();setLogin(true)}
async function load(){const {data,error}=await db.from("products").select("*").order("created_at",{ascending:false});if(error){list.textContent=error.message;return}const cats=[...new Set((data||[]).map(x=>x.category))];category.innerHTML=cats.map(x=>`<option>${x}</option>`).join("");catsDiv(cats,data||[]);list.innerHTML=(data||[]).map(x=>`<div class="item"><img src="${x.image_url||""}"><div><b>${x.name}</b><small>${x.code} · ${x.category} · ₹${x.price}</small></div><div class="actions"><button onclick='edit(${JSON.stringify(x)})'>EDIT</button><button class="${x.is_active?"hide":"show"}" onclick="toggle('${x.id}',${x.is_active})">${x.is_active?"HIDE":"SHOW"}</button></div></div>`).join("")||"No sarees yet."}
function catsDiv(cats,data){catsEl=document.getElementById("cats");catsEl.innerHTML=cats.map(c=>`<div class="topcat"><span>${c} (${data.filter(x=>x.category===c).length})</span><button onclick="renameCat('${c.replace(/'/g,"\\'")}')">RENAME</button></div>`).join("")}
addcat.onclick=async()=>{const n=newcat.value.trim();if(!n)return;const {data}=await db.from("products").select("id").limit(1);alert("To create an empty collection, add the first saree using this new name in the category field. Existing collections are created automatically.");newcat.value=""}
function edit(x){editid.value=x.id;code.value=x.code;pname.value=x.name;category.value=x.category;price.value=x.price;desc.value=x.description||"";scrollTo({top:app.offsetTop,behavior:"smooth"})}
function clearForm(){editid.value="";code.value=pname.value=price.value=desc.value="";photo.value=""}clear.onclick=clearForm;
async function saveS(){let id=editid.value,image_url=null;if(photo.files[0]){const f=photo.files[0],path=Date.now()+"-"+f.name.replace(/[^a-zA-Z0-9._-]/g,"");const u=await db.storage.from("sarees").upload(path,f,{upsert:true});if(u.error)return alert(u.error.message);image_url=db.storage.from("sarees").getPublicUrl(path).data.publicUrl}const row={code:code.value.trim(),name:pname.value.trim(),category:category.value,price:Number(price.value),description:desc.value.trim()};if(image_url)row.image_url=image_url;const r=id?await db.from("products").update(row).eq("id",id):await db.from("products").insert(row);if(r.error)alert(r.error.message);else{alert("Saree saved");clearForm();load()}}save.onclick=saveS;
async function toggle(id,state){const r=await db.from("products").update({is_active:!state}).eq("id",id);if(r.error)alert(r.error.message);else load()}
async function renameCat(old){const n=prompt("New collection name",old);if(!n||n===old)return;const r=await db.from("products").update({category:n}).eq("category",old);if(r.error)alert(r.error.message);else load()}
(async()=>{if(init()){const {data}=await db.auth.getSession();if(data.session){setLogin(false);load()}}})();